In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)


2


In [2]:
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)
print("Original shape:", arr.shape)

# Reshape to a 2D array 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
print("New shape:", reshaped_arr.shape)

Original array: [1 2 3 4 5 6]
Original shape: (6,)
[[1 2 3]
 [4 5 6]]
New shape: (2, 3)


In [3]:
def pythonsum(n):
   a = range(n)
   b = range(n)
   c = []
   for i in range(n):
       a[i] = i ** 2
       b[i] = i ** 3
       c.append(a[i] + b[i])
   return c

In [4]:
def pythonsum(n):
    a = [0] * n
    b = [0] * n
    c = []
    for i in range(n):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c


In [5]:
import numpy as np
def numpysum(n):
  a = np.arange(n) ** 2  
  b = np.arange(n) ** 3
  c = a + b #element wise adding 
  return c

In [6]:
numpysum(3)

array([ 0,  2, 12])

In [7]:
#Creating Arrays from Sequences
#a list of numbers will create a 1D array
#a list of lists will create a 2D array
#further nested lists will create higher-dimensional arrays
#In general, any array object is called an ndarray in NumPy

In [8]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [1]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129])

In [2]:
import numpy as np
np.array([127, 128, 129], dtype=np.int8)
# we are getting error here,since numpy stops allowing conversion from out of bound integer to integer array

C:\Users\syeds\AppData\Local\Temp\ipykernel_19600\3984902477.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)
C:\Users\syeds\AppData\Local\Temp\ipykernel_19600\3984902477.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8)


array([ 127, -128, -127], dtype=int8)

In [3]:
#functions for creating arrays
import numpy as np
np.arange(2, 3, 0.1) #?

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [4]:
#best practice for numpy.arange is to use integer start, end, and step values.

In [5]:
np.linspace(1., 4., 6)


array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [6]:
#2D Array Creation
#The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander define 
#properties of special matrices represented as 2D arrays.
import numpy as np
#np.eye(3)
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [7]:
np.eye(3, 5, k=-2) #optional k argument

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [8]:
import numpy as np
#np.diag([1, 2, 3])
np.diag([1, 2, 3], 1)
#a = np.array([[1, 2], [3, 4]])
#np.diag(a)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [9]:
#Vandermonde Matrix
import numpy as np
#np.vander(np.linspace(0, 2, 5), 2)
#np.vander([1, 2, 3, 4], 2)
#np.vander((1, 2, 3, 4), 4)

In [10]:
np.vander(np.linspace(0, 2, 5), 2)
#np.linspace(0, 2, 5) → [0. , 0.5, 1. , 1.5, 2. ]

np.vander([1, 2, 3, 4], 2)
#Input: [1, 2, 3, 4]
# No of Columns 2


array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])